remote_theme: daattali/beautiful-jekyll@6.0.1
title: Antón Vega - Bioinformatician
author: Antón Vega
description: "Personal website of Antón Vega, bioinformatician specializing in computational biology and data analysis"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About: "about"
  Projects: "projects"
  Publications: "publications"
  Blog: "blog"
  CV: "cv"
  Contact: "contact"
  
# Multi-language support
languages:
  - code: "en"
    name: "English"
  - code: "es"
    name: "Español"
  - code: "ca"
    name: "Català"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
avatar: "/assets/img/avatar.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
# title-img: /assets/img/logo.png

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "antonvegamendez@gmail.com"
  github: antonvegam
  linkedin: antonvega-bioinformatics
  ORCID: https://orcid.org/0009-0004-0525-6635
  # ResearchGate can be added as a custom link if needed

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true
  facebook: false
  vk: false

# How to display the link to your website in the footer
url-pretty: "antonvega.github.io"

# SEO and metadata
keywords: "bioinformatics,computational biology,data analysis,genomics,python,R,machine learning"

# Content settings
title-on-all-pages: true
excerpt_length: 75
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false  # Set to true if you want edit buttons

# Navigation settings
navbar-var-length: true

######################################
# --- Dark Professional Theme --- #
######################################

# Dark theme color scheme for professional bioinformatics website
page-col: "#1a1a1a"           # Dark background
text-col: "#e0e0e0"           # Light text
link-col: "#64b5f6"           # Professional blue links
hover-col: "#42a5f5"          # Lighter blue on hover
navbar-col: "#2d2d2d"         # Dark navbar
navbar-text-col: "#ffffff"    # White navbar text
navbar-border-col: "#404040"  # Subtle border
footer-col: "#2d2d2d"         # Dark footer
footer-text-col: "#b0b0b0"    # Light gray footer text
footer-link-col: "#64b5f6"    # Blue footer links
footer-hover-col: "#42a5f5"   # Hover effect

# Optional: Add a subtle pattern or gradient
# navbar-img: "/assets/img/navbar-bg.png"
# footer-img: "/assets/img/footer-bg.png"
# page-img: "/assets/img/page-bg.png"

################
# --- Misc --- #
################

# Date Format
date_format: "%B %-d, %Y"

# Timezone
timezone: "Europe/Madrid"

# Pagination
paginate: 8
paginate_path: "/blog/page:num/"

#################################################################################
# --- Technical Configuration --- #
#################################################################################

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year-:month-:day-:title/

# Kramdown settings for better code highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # Disabled for static site
      social-share: true
      show-avatar: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

# Collections for organizing content
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/

# Exclude files from build
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/
  - node_modules/
  - "*.gem"

# Required plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from



social:
  name: Antón Vega
  links:
    - https://github.com/antonvegam
    - https://www.linkedin.com/in/ant%C3%B3n-vega-m%C3%A9ndez-b85a19238/

# Additional features
breadcrumbs: true
read_time: true
words_per_minute: 200

# Custom CSS for bioinformatics-specific styling
custom-css: "/assets/css/custom.css"
custom-js: "/assets/js/custom.js"
